import Head from 'next/head'
import { useState, useEffect } from 'react'

export default function Home() {

  const [sensorsData, setData] = useState(null)
  const [isLoading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true);
    fetch('/api/get_stored_data')
      .then((res) => res.json())
      .then((data) => {
        console.log(data);
        setData(data);
        setLoading(false);
      })
  }, []);

  return (
    <>
      <Head>
        <title>Home Plant Lab</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p className='text-lg'>Raspberry Pi Home Lab</p>
        {!isLoading && sensorsData && sensorsData.length > 0 && sensorsData.map((item) => {
          return <div key={item.id}>
            <p className="text-3xl">Temperature: {item.temperature}</p>
            <p>Humidity: {item.humidity}</p>
            <p>Measured: {new Date(item.measure_date).toLocaleString()}</p>
          </div>
        })}
      </main>
    </>
  )
}